import { useState } from 'react';
import useGitHubRepos from '../../hooks/useGitHubRepos';
import useVercelProjects from '../../hooks/useVercelProjects';
import ProjectCard from './ProjectCard';
import Modal from '../common/Modal';
import { AnimatePresence, motion } from 'framer-motion';
import { fetchRepoReadme } from '../../lib/api/github';
import type { MergedProject, VercelProject, GitHubRepo } from '../../types';

// ─── Name Aliases ───────────────────────────────────────────────────────────
// Maps Vercel project names → GitHub repo names when they differ.
// Key = vercel name (lowercase), Value = { github: repo name, display: title to show }
const NAME_ALIASES: Record<string, { github: string; display: string }> = {
    'geo-pol':                { github: 'geopol',             display: 'GeoPol' },
    'wedaforecast':           { github: 'weather-app',        display: 'WedaForecast' },
    'password-generator-eng': { github: 'password-generator', display: 'Password Generator' },
};

// ─── Exclusion List ─────────────────────────────────────────────────────────
// Vercel projects to hide (lowercase names)
const EXCLUDED_PROJECTS = new Set([
    'earo-invoice',
    'casdy',
    'my-website',
]);

// ─── Preview Images ─────────────────────────────────────────────────────────
// Maps project names (lowercase) → local screenshot paths in public/previews/
// Generated by: node scripts/capture-previews.mjs
const PREVIEW_IMAGES: Record<string, string> = {
    'wedaforecast':           '/previews/wedaforecast.png',
    'geopol':                 '/previews/geopol.png',
    'planr':                  '/previews/planr.png',
    'password-generator-eng': '/previews/password-generator-eng.png',
};

const ProjectsGrid = () => {
    const { repos, loading: ghLoading, error: ghError } = useGitHubRepos('casdy');
    const { projects: vercelProjects, loading: vLoading, error: vError } = useVercelProjects();

    const [selectedProject, setSelectedProject] = useState<MergedProject | null>(null);
    const [readmeContent, setReadmeContent] = useState<string | null>('');

    const loading = ghLoading || vLoading;
    const error = ghError || vError;

    // ─── Merge Logic ────────────────────────────────────────────────────────────

    // 1. Filter Vercel projects: active production URL + not excluded
    const activeVercelProjects = vercelProjects.filter(
        (p: VercelProject) =>
            p.targets?.production?.url &&
            !EXCLUDED_PROJECTS.has(p.name.toLowerCase())
    );

    // 2. Build GitHub repo lookup by lowercase name
    const githubByName = new Map<string, GitHubRepo>();
    repos.forEach((r: GitHubRepo) => {
        githubByName.set(r.name.toLowerCase(), r);
    });

    // 3. Track which GitHub repos have been consumed by a Vercel merge
    const consumedGitHubNames = new Set<string>();

    // 4. Process Vercel projects → merge with matching GitHub repos
    const mergedMap = new Map<string, MergedProject>();

    activeVercelProjects.forEach((vp: VercelProject) => {
        const vpKey = vp.name.toLowerCase();
        const alias = NAME_ALIASES[vpKey];

        // Find the matching GitHub repo (by alias or exact name)
        const ghKey = alias ? alias.github.toLowerCase() : vpKey;
        const ghRepo = githubByName.get(ghKey);

        const displayName = alias ? alias.display : (ghRepo ? ghRepo.name : vp.name);

        const merged: MergedProject = {
            name: displayName,
            description: ghRepo?.description ?? vp.description,
            liveUrl: `https://${vp.targets.production!.url}`,
            githubUrl: ghRepo?.html_url ?? null,
            homepage: ghRepo?.homepage ?? null,
            framework: vp.framework,
            language: ghRepo?.language ?? null,
            languages: ghRepo?.languages ?? [],
            topics: ghRepo?.topics ?? [],
            isLive: true,
            key: `live-${vp.id}`,
            githubRepoName: ghRepo?.name ?? null,
            previewImage: PREVIEW_IMAGES[vpKey] ?? PREVIEW_IMAGES[ghKey] ?? PREVIEW_IMAGES[displayName.toLowerCase()] ?? null,
        };

        mergedMap.set(vpKey, merged);
        consumedGitHubNames.add(ghKey);
    });

    // 5. Add remaining GitHub repos that weren't consumed as "ARCHIVE" cards
    repos.forEach((repo: GitHubRepo) => {
        const key = repo.name.toLowerCase();
        if (consumedGitHubNames.has(key)) return;
        if (EXCLUDED_PROJECTS.has(key)) return;

        const merged: MergedProject = {
            name: repo.name,
            description: repo.description,
            liveUrl: null,
            githubUrl: repo.html_url,
            homepage: repo.homepage,
            framework: null,
            language: repo.language,
            languages: repo.languages ?? [],
            topics: repo.topics ?? [],
            isLive: false,
            key: `archive-${repo.id}`,
            githubRepoName: repo.name,
            previewImage: PREVIEW_IMAGES[key] ?? null,
        };

        mergedMap.set(key, merged);
    });

    // 6. Sort: live projects first, then archives
    const allProjects = Array.from(mergedMap.values()).sort((a, b) => {
        if (a.isLive && !b.isLive) return -1;
        if (!a.isLive && b.isLive) return 1;
        return 0;
    });

    const liveCount = allProjects.filter(p => p.isLive).length;
    const archiveCount = allProjects.filter(p => !p.isLive).length;

    // ─── Handlers ───────────────────────────────────────────────────────────────

    const handleViewDetails = async (project: MergedProject) => {
        setSelectedProject(project);
        setReadmeContent(null); // Show loading spinner

        // Fetch README for context below the preview
        if (project.githubRepoName) {
            try {
                const text = await fetchRepoReadme('casdy', project.githubRepoName);
                setReadmeContent(text);
            } catch (err) {
                console.error("Error fetching README:", err);
                setReadmeContent('# No README available\nCould not load project documentation.');
            }
        } else {
            setReadmeContent('# ' + project.name + '\n\n' + (project.description || 'Live deployment on Vercel.'));
        }
    };

    const closeModal = () => {
        setSelectedProject(null);
        setReadmeContent('');
    };

    // ─── Render ─────────────────────────────────────────────────────────────────

    if (loading) {
        return (
            <div id="projects" className="py-20 bg-transparent">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="text-center mb-16">
                        <h2 className="text-3xl md:text-4xl font-bold font-display text-white mb-4">The Node Grid</h2>
                        <p className="text-zinc-300 max-w-2xl mx-auto font-mono text-sm">
                            Connecting to data sources...
                        </p>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {[...Array(6)].map((_, i) => (
                            <div key={i} className="bg-slate-800/50 animate-pulse border border-slate-700/50 rounded-xl h-64" />
                        ))}
                    </div>
                </div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="text-center py-20">
                <p className="text-red-400 font-mono">[ ERROR ] {error}</p>
            </div>
        );
    }

    return (
        <div id="projects" className="py-20 bg-transparent">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="text-center mb-16">
                    <motion.h2
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        className="text-3xl md:text-4xl font-bold font-display text-white mb-4"
                    >
                        The Node Grid
                    </motion.h2>
                    <motion.p
                        initial={{ opacity: 0 }}
                        whileInView={{ opacity: 1 }}
                        transition={{ delay: 0.2 }}
                        className="text-zinc-300 max-w-2xl mx-auto font-mono text-sm"
                    >
                        <span className="text-cyan-400">{liveCount} live nodes</span>
                        {' // '}
                        <span className="text-purple-400">{archiveCount} archive nodes</span>
                        {' // connected'}
                    </motion.p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    {allProjects.map((project, index) => (
                        <motion.div
                            key={project.key}
                            initial={{ opacity: 0, y: 30 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ delay: index * 0.08 }}
                            viewport={{ once: true }}
                        >
                            <ProjectCard
                                project={project}
                                onDetails={handleViewDetails}
                            />
                        </motion.div>
                    ))}
                </div>
            </div>

            <AnimatePresence mode="wait">
                {selectedProject && (
                    <Modal
                        isOpen={!!selectedProject}
                        onClose={closeModal}
                        project={selectedProject}
                        content={readmeContent}
                    />
                )}
            </AnimatePresence>
        </div>
    );
};

export default ProjectsGrid;
